Fixed issue with SSL certificate
Some users might have issues with https, which is set default.
Explicitly set scheme to http.

geopy.exc.GeocoderServiceError: <urlopen error [SSL:
CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>